define a schema for relation members
ideditor/schema-builder pull request #174
Opened 2024-12-20 09:01 UTC by k-yle

Closes #134

This is my proposal for a schema to define the roles of a relation. In summary:
- presets can have a new field called `relation`
- to avoid duplication, there is also `relationCrossReference`, similar to `stringsCrossReference`
- each role is defined with a default (`en-US`) label, just like presets & fields.

Example for `type=boundary`:
```jsonc
{
  "relation": {
    "allowDuplicateMembers": false,
    "members": [
      {
        "roles": { "inner": "Inner" },
        "geometry": ["line", "area"],
        "matchTags": [{}]
      },
      {
        "roles": { "outer": "Outer" },
        "geometry": ["line", "area"],
        "matchTags": [{}],
        "min": 1
      },
      {
        "roles": { "admin_centre": "Capital", "label": "Label" },
        "geometry": ["point", "vertex"],
        "matchTags": [{ "place": "*" }],
        "max": 1
      }
    ]
  }
}
```

Regarding `matchTags`:
- `[{}]` means any tags
- `[]` means no tags (it will never match, this is unhelpful)
- `[{ a: 1, b: 2 }]` means a=1 AND b=2
- `[{ a: 1 }, { b: 2 }]` means a=1 OR b=2

2024-12-20 09:27 UTC, 1ec5 reviewed
Thanks!

2024-12-20 09:27 UTC, 1ec5 commented on schemas/preset.json
> +                                "description": "Map of roles to their label in the default language. An empty string is allowed as key."
How useful is it to be able to combine multiple roles in the same role definition? Are there any relation types with lots of very similar roles that would have verbose definitions?

2024-12-20 09:27 UTC, 1ec5 commented on schemas/preset.json
> +                            "matchTags": {
Would it be useful to define something for documentation here too? It would be nice to be able to show a tooltip with a description of the role, for example to clarify that “Capital” (`admin_centre`) is a capital city, not a government headquarters building. The `matchTags` should prevent further mixups, but the user might encounter an already mistagged role and need to know the difference.

The wiki has [a number of data items](https://wiki.openstreetmap.org/wiki/Special:WhatLinksHere/Item:Q4667) about roles, but none of them are tied to article titles. There’s a separate set of articles about roles under the “Role:” pseudonamespace, but these mostly serve as disambiguation pages, directing readers to the relation type pages.

We could set up more specific, per–relation type pages that have predictable titles and are linked to the data items. If so, then we wouldn’t necessarily need anything about documentation in the schema. Alternatively, we could add a property to the schema that indicates the QID of the data item about the role in the particular relation type.

2024-12-20 10:00 UTC, k-yle commented on schemas/preset.json
> +                            "matchTags": {
great question, I wasn't aware of these data items! It's a shame that we can't query the wikibase API by [_P21 permanent relation role ID_](https://osm.wiki/Property:P21)

What approach do you think is better? I can see downsides of both methods:
- Creating wiki pages like `Role:multipolygon=outer` might confuse people because the syntax for [_P21_](https://osm.wiki/Property:P21) looks very similar to an OSM tag. `Role:multipolygon/outer` might be less confusing. I assume these pages would be stubs or redirect pages?
- Storing the QID for each role in this repository would be cumbersome and error-prone

2024-12-20 10:07 UTC, k-yle commented on schemas/preset.json
> +                                "description": "Map of roles to their label in the default language. An empty string is allowed as key."
PTv2's `stop(_on_demand)?(_exit_only|_entry_only)?` is probably the most verbose (likewise for `platform_*`). That would be 6 entries in a single JSON block.


So, there would be 13+ translatable strings for the PTv2 schema. I'm not sure how we could optimise this further

```jsonc
"members": [
 // x6 stop_*                vertex
 // x6 platform_*            line + area
 // x1 (empty string)        line
 // x0 (other)               any geometry
]
```

2024-12-21 02:06 UTC, 1ec5 commented on schemas/preset.json
> +                                "description": "Map of roles to their label in the default language. An empty string is allowed as key."
Ah OK, that’s what I was missing – a case where a relation type has lots of very similar roles.

2024-12-21 02:20 UTC, 1ec5 commented on schemas/preset.json
> +                            "matchTags": {
> I assume these pages would be stubs or redirect pages?

I was thinking of creating them as redirect pages for now, since there are already other pages that go into more detail, but in principle there could be full-fledged pages in the future.

> Creating wiki pages like `Role:multipolygon=outer` might confuse people because the syntax for [_P21_](https://osm.wiki/Property:P21) looks very similar to an OSM tag.

Or maybe “Relation:multipolygon/outer”, assuming a relation type will never have a slash in it. Both this format and “Role:multipolygon/outer” carry the downside that, if the Translate extension is ever installed on the wiki (openstreetmap/operations#649), it’ll start using subpages for translations, with ISO language codes as subpage names. The `to` role will conflict with Tongan, maybe others too. [Blank roles](https://wiki.openstreetmap.org/wiki/Item:Q16079) would also wind up with an awkward page title. Maybe something more verbose but less ambiguous like “Relation:multipolygon/Roles/outer” or “Role:outer (multipolygon)” would be more future-proof. We could [ask the wiki community](https://wiki.openstreetmap.org/wiki/Talk:Wiki) what they’d prefer.

2024-12-21 09:42 UTC, k-yle commented on schemas/preset.json
> +                            "matchTags": {
https://github.com/openstreetmap/operations/issues/903 seems like the simplest solution to me, since it doesn't involve mass-creating wiki pages, nor inventing a new syntax for these pages' names. 

The only thing we would need to store in this repository is the [P41](https://osm.wiki/Property:P41) for each relation. Then we can lookup the documentation for each role using the same approach as presets & fields.  

I'm not very familiar with mediawiki, but [we're running v1.39](https://osm.wiki/Special:Version), so there's no major update required to install this extension?

2024-12-26 07:03 UTC, 1ec5 commented on schemas/preset.json
> +                            "matchTags": {
There aren’t any technical blockers as far as I know. But that request has been languishing for a while, so it might be quicker to just create the redirects on the wiki as a stopgap.

2024-12-31 12:26 UTC, DujaOSM commented on schemas/preset.json
> +                            "matchTags": {
For what it's worth, following a request on Talk:Wiki that cited this discussion, I added data item [Descriptions](https://wiki.openstreetmap.org/w/index.php?title=Special%3AContributions&target=Duja&namespace=120&tagfilter=&topOnly=1&start=&end=&limit=500) for two dozen most common relation roles. Only a few are linked to Wiki articles proper (mostly unusable), such as [Q22741](https://wiki.openstreetmap.org/wiki/Item:Q22741) and a few I added are linked to redirects (such as [Q22737](https://wiki.openstreetmap.org/wiki/Item:Q22737) ).

2025-01-05 05:03 UTC, k-yle commented on schemas/preset.json
> +                            "matchTags": {
I've added a property called `relation.id` to the schema, which would store the [`P41`](https://osm.wiki/Property:P41) value, such as [`multipolygon`](https://osm.wiki/Relation:multipolygon). This will be needed regardless of how we query the wiki. 

> [[...]](#discussion_r1894536451) We could [ask the wiki community](https://osm.wiki/Talk:Wiki) what they’d prefer.

It sounds like creating redirect or stub pages for each role isn't a popular idea.... Which means there's no way for iD to query this data without the WikibaseCirrusSearch extension.

2025-01-05 09:19 UTC, 1ec5 commented on schemas/preset.json
> +                            "matchTags": {
Using the new [relation member roles <small>(P54)</small>](https://wiki.openstreetmap.org/wiki/Property:P54) property, the existing `wbgetentities` response now includes the QID of the item for each role pertaining to the relation type. We can get the ID and descriptions of each item in a separate `wbgetentities` call. This isn’t as streamlined as the redirect approach, but it should still be workable, since none of the relation types has more than a handful of itemized roles.

Alternatively, if we’re comfortable with relying on the apparent English label naming convention for these role items, we can issue [a single `wbsearchentities` call](https://wiki.openstreetmap.org/wiki/Special:ApiSandbox#action=wbsearchentities&format=json&search=boundary%20relation&language=en&strictlanguage=1&type=item) in the form “_type_ relation” to get the relation type item plus all the associated role items. However, this is inherently limited to getting the description in the user’s language; we wouldn’t be able to get any image or other metadata.

2025-01-05 09:28 UTC, 1ec5 commented on schemas/preset.json
> +                            "matchTags": {
I also just noticed that a bunch of the role items already have their sitelinks set to nonexistent pages like “Relation:boundary=admin centre”, [as documented](https://wiki.openstreetmap.org/wiki/Data_items#Relation_roles). This makes it possible to access these items directly using `wbgetentities`.

2025-01-06 22:55 UTC, k-yle commented on schemas/preset.json
> +                            "matchTags": {
in that case, I believe that https://github.com/ideditor/schema-builder/compare/5157ab..31f9af means that the schema now has all the information required to construct an API query for the documentation (?)

2025-07-22 11:18 UTC, k-yle commented
updated the PR description about `matchTags`. Instead of the confusing `[{}]` syntax, you can just omit `matchTags`.

2025-10-24 08:40 UTC, k-yle commented
documentation added

2025-10-24 09:49 UTC, FloEdelmann commented on schemas/preset.json
> +                    }
```suggestion
                    "additionalProperties": {
                        "type": "string"
                    },
                    "minProperties": 1
```

2025-10-24 09:49 UTC, FloEdelmann commented on schemas/preset.json
> +                                },
```suggestion
                            "geometry": {
                                "type": "array",
                                "uniqueItems": true,
                                "items": {
                                    "$ref": "field.json#/$defs/Geometry"
                                },
```

2025-10-24 09:49 UTC, FloEdelmann commented on schemas/preset.json
> +                                    }
```suggestion
                                    "additionalProperties": {
                                        "type": "string"
                                    },
                                    "minProperties": 1
```

2025-10-24 10:41 UTC, k-yle commented on schemas/preset.json
> +                                    }
ah i forgot about https://github.com/ideditor/schema-builder/pull/174#issuecomment-3102287444. so this does make sense, thanks!

2025-12-16 11:31 UTC, k-yle commented
hey @tyrasd, is there anything else that needs to be changed here? I've resolved the latest batch of merge conflicts

2026-02-27 16:44 UTC, matkoniecz commented on README.md
> +    "id": "restriction", // value of https://osm.wiki/Property:P41
```suggestion
    "id": "restriction", // value of https://osm.wiki/Property:P41 from matching item, in this case https://wiki.openstreetmap.org/wiki/Item:Q16054 - note that multiple relation entries may have the same `id` value
```

2026-02-27 16:46 UTC, matkoniecz commented on README.md
> +        "roleLabel": "From", // The label for the role, in the default language.
```suggestion
        "roleLabel": "From", // The label for the role, in the default language. An empty string is allowed
```

maybe for labels it is more implied to be OK, but previous line specifies it explicitly so maybe also mention for clarity?

2026-02-27 16:46 UTC, matkoniecz commented on README.md
> +        "max": 1, // maxmium number of times that this role must appear in the relation
```suggestion
        "max": 1, // maximum number of times that this role must appear in the relation
```

2026-02-27 16:47 UTC, matkoniecz commented on README.md
> +        "max": 1,
wait, multiple vias are OK!

https://github.com/Project-OSRM/osrm-backend/issues/4439
```suggestion
```

2026-02-27 16:49 UTC, matkoniecz commented on README.md
> +            "$1": "yes" // 👈 here
```suggestion
            "$1": "yes" // 👈 here this tag is required to appear on members
```

try being more clear (not sure is it actually more clear)

2026-02-27 16:55 UTC, matkoniecz commented on schemas/preset.json
> +                                "description": "The label for the role, in the default language."
```suggestion
                                "description": "The label for the role, in the default language. An empty string is allowed."
```

maybe for labels it is more implied to be OK, but previous line specifies it explicitly so maybe also mention for clarity?

(there is a similar suggestion below)

2026-02-27 17:00 UTC, matkoniecz commented on README.md
> +For example, if a relation with [`type=route`](https://osm.wiki/Tag:type=route) + [`route=XXXX`](https://osm.wiki/Key:route) has a member with a role of `stop`, then that member must have a tag of `X
what if relation has no such tag? is it then noop or is it requiring such tag to not be present?

Or something else?

2026-02-27 17:00 UTC, matkoniecz reviewed
for now I focused on docs as I do not understand (yet?) the actual code

2026-02-28 07:13 UTC, matkoniecz commented on schemas/preset.json
> +                    "description": "Set to `true` if the same OSM feature is allowed to appear multiple times in the relation's members. The."
"The." at the end seems to be not needed or terminate prematurely.

2026-02-28 12:49 UTC, k-yle commented on README.md
> +For example, if a relation with [`type=route`](https://osm.wiki/Tag:type=route) + [`route=XXXX`](https://osm.wiki/Key:route) has a member with a role of `stop`, then that member must have a tag of `X
good question. I think this check would just be skipped?

2026-02-28 12:52 UTC, k-yle commented on README.md
> +            "$1": "yes" // 👈 here
thanks, I've applied all these suggestions, with a few minor tweaks

2026-02-28 12:56 UTC, k-yle commented
> for now I focused on docs as I do not understand (yet?) the actual code

should i open some PRs in iD to showcase how this data will be used? For example:
1. translated labels in the _relation role_ dropdown field  (already implemented 1 year ago)
2. automatic selection of roles when adding a way to relation (e.g. choose `stop` or `platform` automatically for `stop_area` relations)
3. enforce constraints, like preventing adding roads directly to a `super_route` or `route_master`.
4. relation validator (already implemented 2 years ago, [old broken demo here](https://kyle.kiwi/iD/#map=19.66/-36.79654/174.76618&id=r11258777))

<img width="200" alt="image" src="https://github.com/user-attachments/assets/0afe7953-e82e-4590-a17c-2e5583699e9d" />

2026-02-28 13:03 UTC, matkoniecz commented
I think that for this specific PR next step from my side would be to try diffing into it and understanding what is going on.

I will do this now if this PR is not abandoned. I was worried it may be given that it was submitted AD 2024, that is why I left mostly surface-level comments without deeper understanding, to probe is it still alive. I will now try to make a more proper review.

2026-02-28 13:43 UTC, k-yle commented
definitely not abandoned. There are huge number of issues in iD which are blocked by this PR (also because it's also blocking #196)

2026-03-04 03:55 UTC, matkoniecz commented on schemas/field.json
> +              "$ref": "#/$defs/Geometry"
what is the reason/benefit of this change? Is it required?

2026-03-04 03:56 UTC, matkoniecz commented on schemas/preset.json
> +            "description": "A preset can reference the relation schema from another preset",
```suggestion
            "description": "A preset can reference the relation schema from another preset instead of defining the same schema again",
```

clarify/imply/hint that it duplicates referenced one

2026-03-04 03:59 UTC, matkoniecz commented on schemas/preset.json
> +                "optionalTags": {
maybe different name would be nicer? this does not hint well how it is used

`recordTags` ? `rememberTags` ? `referencedTags` ?

2026-03-04 04:01 UTC, matkoniecz commented on README.md
> +      "route": "$1", // 👈 the tag value can be referenced below using $1
what happens when multiple values are set to `$1`?

Can value be set to arbitrary text?

2026-03-04 04:02 UTC, matkoniecz commented on README.md
> +For example, if a relation with [`type=route`](https://osm.wiki/Tag:type=route) + [`route=XXXX`](https://osm.wiki/Key:route) has a member with a role of `stop`, then that member must have a tag of `X
I guess that either would be fine (though I have not looked thoroughly at possible relation schemas that would use it). 

But having it defined rather than leaving it as undefined operation seems prudent.

2026-03-04 04:04 UTC, matkoniecz commented on README.md
> +* `relation.id` – a string. This is the “permanent relation type ID”, it should match the value of [permanent relation type ID<sup><code>P41</code></sup>](https://osm.wiki/Property:P41) in the OSM wi
```suggestion
* `relation.id` – a string. This is the “permanent relation type ID”, it must match the value of [permanent relation type ID<sup><code>P41</code></sup>](https://osm.wiki/Property:P41) in the OSM wiki’s wikibase system.
```
?

2026-03-04 04:04 UTC, matkoniecz commented on README.md
> +* `relation.id` – a string. This is the “permanent relation type ID”, it should match the value of [permanent relation type ID<sup><code>P41</code></sup>](https://osm.wiki/Property:P41) in the OSM wi
BTW, why do we even need this id?

2026-03-04 04:06 UTC, matkoniecz commented on README.md
> +* `relation.members` – an array of objects, which lists every member that is permitted (see below).
```suggestion
* `relation.members` – an array of objects, which lists every member format that is permitted (see below).
```

well, technically it is not defining members - members would be specific OSM elements

but that may be going too far on technically correct front

2026-03-04 04:07 UTC, matkoniecz commented on README.md
> +    "allowDuplicateMembers": true,
why left turn would allow duplicate members?

U-turn would need it, but why left-turn would do this?

If it is to allow u-turn to reuse it, then maybe u-turn should be defined separately and allow other restrictions to have this bit of extra feedback?

2026-03-04 04:08 UTC, matkoniecz commented on README.md
> +        "roleLabel": "From", // The label for the role, in the default language. An empty string is allowed
```suggestion
        "role": "from", // The relation role. An empty string is allowed.
        "roleLabel": "From", // The label for the role, in the default language. An empty string is allowed.
```

Maybe either do sentences or not for both first and second?

2026-03-04 04:14 UTC, matkoniecz commented
General question: how I would test it?

https://github.com/ideditor/schema-builder sadly seems to not have CONTRIBUTING.md beyond legalese at https://github.com/ideditor/schema-builder?tab=readme-ov-file#contributing

I guess I would modify https://github.com/openstreetmap/id-tagging-schema to add such relation definition, modify https://github.com/openstreetmap/id-tagging-schema/blob/main/scripts/build.js to reference this branch (or my local clone of schema-builder set to this branch), run build script and inspect output?

And intentionally trigger build failures with bad relation definitions that should be caught.

2026-03-05 11:58 UTC, k-yle commented
> General question: how I would test it?

yeah, this repo setup is really annoying for testing. Off topic, but I think we should merge the last 3 PRs here, release v7, then abandon this repo (as proposed in #35). But we can discuss this after v7 is released.


The easier way to test it would be to checkout https://github.com/openstreetmap/id-tagging-schema/pull/1538, and run `npm install` and `npm run build` and `npm run dist` and restart your IDE.

Then we can check whether the schema format is enforced:

<img width="661" height="242" alt="image" src="https://github.com/user-attachments/assets/4e6040e6-a7c8-4ffa-80b9-3f772c13b792" />

and we can check `interim/source_strings.yaml` to confirm that the `roleLabel`s will be sent to transifex:


<img width="618" height="261" alt="image" src="https://github.com/user-attachments/assets/d72da02a-b1a4-4c12-967b-187deea7baaa" />

2026-03-05 12:03 UTC, k-yle commented on README.md
> +      "route": "$1", // 👈 the tag value can be referenced below using $1
i guess so. We could even completely remove this `$1` idea. I thought it would help for ~~`waterway=*` and~~ `route=*`, but it's over complicating this for ~~2~~ 1 single relation

2026-03-05 12:04 UTC, k-yle commented on schemas/field.json
> +              "$ref": "#/$defs/Geometry"
yes, I didn't want to copy-paste the array twice, so we need to move it to a `$definition`, so that it can referenced in 2 different places

2026-03-05 12:08 UTC, k-yle commented on README.md
> +* `relation.id` – a string. This is the “permanent relation type ID”, it should match the value of [permanent relation type ID<sup><code>P41</code></sup>](https://osm.wiki/Property:P41) in the OSM wi
> BTW, why do we even need this id?

we need this ID so that we can pull translated help infomation from the osmwiki's wikibase system, when the user clicks <img height="30" alt="image" src="https://github.com/user-attachments/assets/33a5c1e0-ec7b-4bd6-a5ba-7f45e3118bc6" />, just like presets and fields. This was discussed extensively in this thread: https://github.com/ideditor/schema-builder/pull/174#discussion_r1893689779

2026-03-05 12:08 UTC, matkoniecz commented on README.md
> +      "route": "$1", // 👈 the tag value can be referenced below using $1
I think it makes sense, and I am not asking it to be removed.

Though I will also not defend it ferociously.

2026-03-05 12:09 UTC, k-yle commented on README.md
> +    "allowDuplicateMembers": true,
good point, bad example, i'll change it to `no_u_turn`

2026-03-05 12:09 UTC, matkoniecz commented
> Off topic, but I think we should merge the last 3 PRs here, release v7, then abandon this repo (as proposed in https://github.com/ideditor/schema-builder/issues/35).

that is part of my motivation for trying to get these PRs processed

2026-03-05 12:13 UTC, k-yle commented on schemas/preset.json
> +                "optionalTags": {
counter question: should be just remove this `optionalTags` and `$1`? It adds a lot complexity and ambiguity, and I'm starting to think we don't need this. see also https://github.com/ideditor/schema-builder/pull/174#discussion_r2889567073

2026-03-05 19:05 UTC, matkoniecz commented
As this is quite substantial change - maybe ping people listed on https://github.com/openstreetmap/id-tagging-schema/wiki/Projects-that-are-using-this-tagging-schema as relevant? So that they can look at proposed schema before merge?

`@Zverik @bryceco @mvexel @bhousel @1ec5` appear to be full list of people worth pinging (for example StreetComplete is not listed as using this part of presets so probably no need to ping `@westnordost`?)

2026-03-06 07:29 UTC, matkoniecz commented
it looks like it is not in our code or code changed in this PR bt on multiple failures you probably should get each error in a separate line..

```
🔬  Validating schema...
data/presets/type/site/climbing/area.json: 
instance.relation.allowDuplicateMembers is not of a type(s) booleaninstance.relation.members[0] requires property "roleLabel"
```

2026-03-06 07:31 UTC, matkoniecz commented on schemas/preset.json
> +                                    "minProperties": 1
note: tried to generate with empty `matchTags` array, it has not generated any errors

2026-03-06 07:32 UTC, matkoniecz commented on schemas/preset.json
> +                                "description": "`*` can be used as a tag value. If multiple array items are specified, only 1 needs to match. If not specified, then any tags are allowed"
within given array item all dictionary key-value pairs must match, right?

2026-03-06 07:32 UTC, matkoniecz commented on schemas/preset.json
> +                                "description": "If unspecified, there is no minimum"
```suggestion
                                "description": "If unspecified, there is no minimum how any times this role must appear in the relation"
```

2026-03-06 07:33 UTC, matkoniecz commented on schemas/preset.json
> +                                "description": "If unspecified, there is no maximum"
```suggestion
                                "description": "If unspecified, there is no maximum how many times this role must appear in the relation"
```

2026-03-06 07:34 UTC, matkoniecz commented on schemas/preset.json
> +                    "description": "Set to `true` if the same OSM feature is allowed to appear multiple times in the relation's members."
```suggestion
                    "description": "Set to `true` if the same OSM feature is allowed to appear multiple times as the relation's member."
```

(????)

2026-03-06 07:35 UTC, matkoniecz commented on schemas/preset.json
> +                "optionalTags": {
as replied there - I do not have strong opinion, I do not ask for removal but I will no defend it ferociously

2026-03-06 07:37 UTC, matkoniecz commented on schemas/preset.json
> +            "description": "A preset can reference the relation schema from another preset, instead of defining the same schema again.",
```suggestion
            "description": "A preset can reference the relation schema from another preset, instead of defining the same schema again. If present, then relation property must not appear.",
```

right?

2026-03-06 07:39 UTC, matkoniecz commented on README.md
> +        "min": 1,
```suggestion
        "min": 1
```

stupid JSON ban on trailing commas applies here, right?

see also elsewhere in example snippet

2026-03-10 11:10 UTC, k-yle commented on schemas/preset.json
> +            "description": "A preset can reference the relation schema from another preset, instead of defining the same schema again.",
yep, done

2026-03-10 11:10 UTC, k-yle commented on schemas/preset.json
> +                    "description": "Set to `true` if the same OSM feature is allowed to appear multiple times in the relation's members."
i reworded the whole thing to simplify it

2026-03-10 11:11 UTC, k-yle commented on README.md
> +        "min": 1,
technically it's fine because of [this line](https://github.com/ideditor/schema-builder/blob/59cb0ad05c88228c0ed7f97f2d66426b1f20354f/README.md?plain=1#L399), but i removed these to keep things consistent

2026-03-10 11:14 UTC, k-yle commented on README.md
> +      "route": "$1", // 👈 the tag value can be referenced below using $1
I've changed my mind, I think we should remove this and keep the first version simple. It can always be added in the future, it would not be a breaking change.

2026-03-10 11:14 UTC, k-yle commented on schemas/preset.json
> +                "optionalTags": {
no longer relevant because of https://github.com/ideditor/schema-builder/pull/174#discussion_r2911019599

2026-03-10 11:15 UTC, k-yle commented on README.md
> +For example, if a relation with [`type=route`](https://osm.wiki/Tag:type=route) + [`route=XXXX`](https://osm.wiki/Key:route) has a member with a role of `stop`, then that member must have a tag of `X
no longer relevant because of https://github.com/ideditor/schema-builder/pull/174#discussion_r2911019599

2026-03-10 11:16 UTC, k-yle commented on schemas/preset.json
> +                                "description": "`*` can be used as a tag value. If multiple array items are specified, only 1 needs to match. If not specified, then any tags are allowed"
yes, is that worth mentioning?

2026-03-10 11:17 UTC, matkoniecz commented on README.md
> +      "route": "$1", // 👈 the tag value can be referenced below using $1
then lets remove it, this is complex enough anyway

2026-03-10 11:26 UTC, matkoniecz commented on schemas/preset.json
> +                                "description": "`*` can be used as a tag value. If multiple array items are specified, only 1 needs to match. If not specified, then any tags are allowed"
I think so, I prefer to be overly specific in specification. Over and over again it turns out that people took obvious things and done reverse than expected.

2026-03-10 11:47 UTC, k-yle commented on schemas/preset.json
> +                                    "minProperties": 1
thanks, fixed now. both cases are flagged:

<img width="618" height="38" alt="image" src="https://github.com/user-attachments/assets/8a7270a3-eb84-4834-a87d-29233891e2fb" />

and

<img width="547" height="41" alt="image" src="https://github.com/user-attachments/assets/8718834e-9c92-4369-a33f-3d82e2023511" />

2026-03-10 11:47 UTC, k-yle commented
> on multiple failures you probably should get each error in a separate line.

it's a one-line-fix so i've added it to this PR.

2026-03-10 13:37 UTC, matkoniecz commented
Based on https://github.com/openstreetmap/id-tagging-schema/wiki/Projects-that-are-using-this-tagging-schema @Zverik @bryceco @mvexel @bhousel @1ec5 - you may be impacted by this change (hopefully in a good way!)

Do you have any feedback on structure proposed here?

See also https://github.com/openstreetmap/id-tagging-schema/pull/1538 for planned specific use of this schema

2026-03-10 15:14 UTC, Zverik commented
Thanks for the heads-up Mateusz! For Every Door, it tries to avoid editing relations (because relations often include ways, and we're not editing geometry), so I guess ignoring this new block would work.

2026-03-10 15:34 UTC, bhousel commented
Thanks, this seems ok.
I'm weakly against the idea of showing users English translations instead of the raw role values, mostly because those raw values really are the defining properties of the relation and they are documented everywhere on the OSM wiki.  In other words, I think showing people the string "Capital" instead of "admin_centre" is likely to lead to confused users.  But the schema definition seems fine and nothing is forcing downstream projects to use the English text labels.

2026-03-10 20:07 UTC, bryceco commented
I'm in favor of this, although I don't have a particular use for it today. I only support editing multipolygons, so this will be useful if my relation support is expanded in the future.

2026-03-10 21:14 UTC, 1ec5 commented
> I'm weakly against the idea of showing users English translations instead of the raw role values, mostly because those raw values really are the defining properties of the relation and they are documented everywhere on the OSM wiki. In other words, I think showing people the string "Capital" instead of "admin_centre" is likely to lead to confused users. But the schema definition seems fine and nothing is forcing downstream projects to use the English text labels.

I did have translation in mind for #134, since some validator warning suggestions already refer to roles in translatable strings. If `admin_centre` versus `label` is confusing to English speakers, then it’s probably even more confusing to say Hungarian speakers. But to your point, an editor like Rapid or iD probably should expose the raw role somewhere, just as it exposes raw keys and values if the user goes looking for them. That could take different forms depending on the editor’s design for memberships. And an editor would be free to just stick with the raw role while using this metadata for other purposes.

2026-03-11 11:32 UTC, matkoniecz commented
Do we need/want more validation such as requiring `role` to be unique in given array?

```
        "members": [
            {
                "role": "outer",
                "roleLabel": "Outer",
                "geometry": [
                    "line",
                    "area"
                ]
            },
            {
                "role": "outer",
                "roleLabel": "Outer",
                "geometry": [
                    "line",
                    "area"
                ]
            }
        ]
```

or should it be valid and is useful in some cases?

2026-03-11 11:44 UTC, k-yle commented
i don't think JSON schema supports that, but maybe there's some experimental magic using [`contains`](https://www.learnjsonschema.com/2020-12/applicator/contains/) and [`maxContains`](https://tour.json-schema.org/content/04-Arrays/07-minContains-and-maxContains) that could solve it. Maybe we could just trust code reviewers to spot mistakes like that?

2026-03-11 11:46 UTC, matkoniecz commented
Maybe it would be enough to define and specify that `role` values should not repeat? Or is it going into too much of handholding even for spec, and sign that I am running out of things to nitpick about?

2026-03-11 11:57 UTC, matkoniecz commented
Similarly: negative max, max smaller than min, empty members array etc.

2026-03-11 11:57 UTC, matkoniecz approved these changes

2026-03-11 12:01 UTC, matkoniecz commented
Though adding also changelog entry would be nice (I want to avoid case where next release ends stuck on reverse engineering changelog entries - here it is less critical as there are no deprecations)

2026-03-16 11:00 UTC, tyrasd requested changes
In general this looks good to me, thanks everyone involved in discussing this in all detail.

The only thing that I stumbled over was the naming of the property `id` for the `P41` relation type identifier: In my opinion, `id` is too closely related to the OSM object id in order to not make this confusing. Suggestion: As this is essentially [about affording](https://github.com/ideditor/schema-builder/pull/174#discussion_r2889595579) the info ℹ️ functionality, why don't we call it like the other properties that exist for the purpose, i.e. `reference`?

2026-03-19 12:30 UTC, k-yle commented
(changed status to draft because it's blocked by #281)

2026-04-17 10:35 UTC, k-yle commented
this has now been rebased onto #281

Since GitHub doensn't support stack diffs [yet](https://github.com/github/roadmap/issues/1218), #281 needs to be merged first, and then the branch from #281 needs to be deleted

2026-04-23 05:17 UTC, matkoniecz commented
> This branch has conflicts that must be resolved

2026-04-30 16:28 UTC, matkoniecz commented
@k-yle can you fix these conflicts?

2026-05-01 12:24 UTC, k-yle commented
done, and tested again by checking out https://github.com/openstreetmap/id-tagging-schema/pull/1538 and running `npm i && npm run dist`

2026-05-12 09:58 UTC, merged