allow multiple `prerequisiteTag`s
ideditor/schema-builder pull request #87
Opened 2023-02-26 05:19 UTC by k-yle

Relates to https://github.com/openstreetmap/iD/pull/9511. This is not a breaking change if that PR is merged first. See https://github.com/openstreetmap/iD/pull/9511 for details.

2023-02-26 06:24 UTC, tordans commented
The docs here also need updating I think. Somewhere here https://github.com/ideditor/schema-builder#prerequisitetag

2023-02-26 08:36 UTC, k-yle commented
thanks @tordans, I've updated the README

2023-03-03 20:20 UTC, tordans commented on README.md
> +- `value`: The value(s) that the key must have. It can be a single value, or a list of possible values.
I assume this is an `AND` situation, right?

```suggestion
- `value`: The value(s) that the key must have. It can be a single value, or a list of possible values. If multiple values are present, all conditions must be met.
```

2023-03-03 22:37 UTC, k-yle commented on README.md
> +- `value`: The value(s) that the key must have. It can be a single value, or a list of possible values.
nah, it's `OR` because you can only have one possible value for an OSM key, e.g.

```js
"prerequisiteTag": { "key": "amenity", "value": ["theatre", "bar"] }
```

this is an unlikely example, some more info in https://github.com/openstreetmap/iD/pull/9511#issuecomment-1454219193

2024-05-25 09:36 UTC, tordans commented
I am wondering about two things…

a. I don't think its great to have a key `value` that can hold an array. It should really be `values` instead.


b. The note on breaking changes is true for iD, but it is not true for GoMap, EveryDoor and other data consumers of the tagging schema repo. 
What would be a good migration path? The easiest would be to make this a major release and explain the update path for the other apps.

I don't see any way to do a soft migration with deprecation and both solutions being present for one release cycle. That would be ideal to release fast but allow consumer apps to update afterwards.

2024-05-25 10:18 UTC, k-yle commented
> a. I don't think its great to have a key `value` that can hold an array. It should really be `values` instead.

Are you suggesting that we allow both `value` XOR `values`? Or should `value` be replaced by `values`?

> b. The note on breaking changes is true for iD, but it is not true for GoMap, EveryDoor and other data consumers of the tagging schema repo.

Based on 544f546, it looks like there's about to be a major release, so we may as well label this as https://github.com/ideditor/schema-builder/labels/breaking

It would be worth prewarning GoMap and EveryDoor, since they're both fetching directly from the main branch...[^1][^2] Ideally all data consumers would be setup to only fetch `v6.x.x`, for example, using `https://unpkg.com/@openstreetmap/id-tagging-schema@6/dist`

[^1]: https://github.com/bryceco/GoMap/blob/c5795d1/src/presets/update.sh#L3
[^2]: https://github.com/Zverik/every_door/blob/a00a2c6/tools/json_to_sqlite.py#L120

2024-05-26 05:45 UTC, tordans commented
> Are you suggesting that we allow both `value` XOR `values`? Or should `value` be replaced by `values`?

I think the best would be to make it a breaking change and migrate everything to `values`. Maybe the builder should have a fallback to listen for `value` as well (and make it an array) so we don't have issues with updating all the code at once over at https://github.com/openstreetmap/id-tagging-schema

> …so we may as well label this as [breaking](https://github.com/ideditor/schema-builder/labels/breaking)

Sounds like the cleanest solution to me.

> It would be worth prewarning GoMap and EveryDoor

Agreed. Lets wait for Martin and then create an issue to ping the known data users.

2024-05-31 09:13 UTC, tordans requested changes

2024-05-31 09:13 UTC, tordans commented on schemas/field.json
>                          "value": {
```suggestion
                        "values": {
```

Following https://github.com/ideditor/schema-builder/pull/87#issuecomment-2131163146 lets make this a breaking change.

2024-05-31 09:14 UTC, tordans requested changes

2024-05-31 09:14 UTC, tordans commented on schemas/field.json
> +                                ]
```suggestion
                                  {
                                      "type": "array",
                                      "items": { "type": "string" }
                                  }
```

Following https://github.com/ideditor/schema-builder/pull/87#issuecomment-2131163146, lets migrate the id-tagging-schema after this was released and merged over there.

2024-05-31 09:35 UTC, tordans commented
On the question of a mayor release and how to inform consumers of the data:

@tyrasd just told me he looked into this with a breaking change in 2022 (eg. [here](https://github.com/bryceco/GoMap/issues/622), [here](https://github.com/Zverik/every_door/issues/452)). Most editors should be using a specific major release. GoMap does not, but that is fine because Bryce pulls the change manually via script so he is informed of breaking changes this way.

2025-02-22 03:29 UTC, k-yle commented
Some specific examples:

Supported by the syntax introduced in this PR:
- `overlap`, `spacing`, and `ōpening`: if `cycle_barrier`=(`double` or `triple`)
- `semark:*:colour_pattern`: if `seamark:*:colour` includes `;`
- `capacity:hgv` if `parking_space`=(`hgv` or `delivery`)
- `seamark:bridge:clearance_height_closed` if `seamark:bridge:category`=(`opening` or `lifting` or `swing` or `bascule` or `drawbridge`)
- `seamark:bridge:clearance_height_open` if `seamark:bridge:category`=`lifting`
- `seamark:bridge:clearance_height` if `seamark:bridge:category`=(`fixed` or `transporter`)
- `seamark:platform:product` if `seamark:platform:category`=(`ōil` or `production` or `ālp` or `fpso`)


**Not** supported by the syntax introduced in this PR:
- `service=*` if “Service Road” preset or (“Road Closed” preset + `construction=service`)
- `fuel:*` if “Fuel Pump” preset or (“Storage Tank” preset + `content=fuel`)
- `maxwidth:physical`: if `cycle_barrier`=(`single` or `diagonal` or `tilted`) OR if “Highway” preset


To support more complex syntax, we would need to move the prerequisiteTags from the `fields/*` files to the `preset/*` files. For example:

```jsonc
{
  // this is a preset
  "fields": [
    "name",
    "access",
    { field: "service", if: { … } }, // possible new syntax for conditional fields
    "operator"
  ]
}
```

2025-02-22 07:08 UTC, tordans commented
Note to self: check https://github.com/ideditor/schema-builder/issues/137#issuecomment-2087984901 for parking:* and the cycleway:* and sidewalk:* cases.

2025-04-30 09:59 UTC, tordans commented
**Schema-Builder-Workshop-Notes:**

0. Handle breaking change communication https://github.com/ideditor/schema-builder/issues/196
1. Update iD to handle the schema – @k-yle has code in his fork
2. Merge here – add `valuesNot`
3. Update `id-tagging-schema`

2025-05-02 06:39 UTC, tordans requested changes
This tries to add the changes we talked about in our meetup https://github.com/ideditor/schema-builder/pull/87#issuecomment-2841451618

The order of the `valuesNot` part is not ideal (it should be below the `valueNot` part) but Github comments did not allow for bigger changes…

2025-05-02 06:39 UTC, tordans commented on README.md
>  - `valueNot`: The value that the key must not have.
```suggestion
- `values`: The values that the key must have.
- `valueNot`: The value that the key must not have.
- `valuesNot`: The values that the key must not have.
```

2025-05-02 06:39 UTC, tordans commented on schemas/field.json
> +                },
```suggestion
                {
                    "$id": "requires-key-equals-values",
                    "type": "object",
                    "properties": {
                        "key": {
                            "description": "The key of the required tag",
                            "type": "string"
                        },
                        "values": {
                            "description": "The values that the tag must have. (alternative to 'valuesNot')",
                            "type": "array",
                            "items": { "type": "string" }
                        }
                    },
                    "additionalProperties": false,
                    "required": ["key", "values"]
                },
                {
                    "$id": "requires-key-not-values",
                    "type": "object",
                    "properties": {
                        "key": {
                            "description": "The key of the required tag",
                            "type": "string"
                        },
                        "values": {
                            "description": "The values that the tag cannot have. (alternative to 'values')",
                            "type": "array",
                            "items": { "type": "string" }
                        }
                    },
                    "additionalProperties": false,
                    "required": ["key", "valuesNot"]
                },
```

2025-07-01 09:18 UTC, merged